<?php

ini_set('display_errors',true);
error_reporting(E_ALL);
// Call UNL_LDAPTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'UNL_LDAPTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../UNL/LDAP.php';
require_once dirname(__FILE__).'/../config.inc.php';

/**
 * Test class for UNL_LDAP.
 * Generated by PHPUnit on 2007-12-14 at 10:18:30.
 */
class UNL_LDAPTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    UNL_LDAP
     * @access protected
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('UNL_LDAPTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = UNL_LDAP::getConnection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * Just tests that you can get a connection to the server.
     */
    public function testGetConnection() {
        $this->assertEquals('UNL_LDAP', get_class($this->object));
    }

    /**
     * @todo Implement testGetAttribute().
     */
    public function testGetAttribute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFirstAttribute().
     */
    public function testGetFirstAttribute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

// Call UNL_LDAPTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'UNL_LDAPTest::main') {
    UNL_LDAPTest::main();
}
?>
